# -*- coding: utf-8 -*-
"""Text Generation with GPT_01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DKWYQgkRqw8hzYDfJtlUO938aOBwhT4v
"""

import torch
print("GPU available:", torch.cuda.is_available())
print("Device name:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No GPU, using CPU")

!pip install -q transformers torch pandas

from transformers import GPT2LMHeadModel, GPT2Tokenizer

model_name = "gpt2"   # small GPT-2 model (124M parameters)

tokenizer = GPT2Tokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token   # GPT-2 has no pad token by default

model = GPT2LMHeadModel.from_pretrained(model_name)

device = "cuda" if torch.cuda.is_available() else "cpu"
model = model.to(device)

print("Model loaded successfully on:", device)

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/dev/Quotes.csv", engine='python')

print("Shape of dataset:", df.shape)
print("Columns:", df.columns.tolist())
df.head()

# drop rows where the quote is missing
df = df.dropna(subset=["quote"])

# remove any extra spaces / newlines inside each quote
df["quote"] = df["quote"].astype(str).str.strip()

# taking a random sample of quotes to keep training time reasonable
SAMPLE_SIZE = 3000
df_sample = df.sample(n=SAMPLE_SIZE, random_state=42).reset_index(drop=True)

# splitting into train (90%) and test (10%)
train_df = df_sample.iloc[: int(0.9 * len(df_sample))]
test_df = df_sample.iloc[int(0.9 * len(df_sample)) :]

print("Train quotes:", len(train_df))
print("Test quotes:", len(test_df))

# saving the quotes into text files
# we separate each quote with the GPT-2 end-of-text token so the model
# learns where one quote ends and another begins

def save_quotes_to_file(quote_list, file_path):
    with open(file_path, "w", encoding="utf-8") as f:
        for q in quote_list:
            f.write(q + tokenizer.eos_token + "\n")

train_file = "quotes_train.txt"
test_file = "quotes_test.txt"

save_quotes_to_file(train_df["quote"].tolist(), train_file)
save_quotes_to_file(test_df["quote"].tolist(), test_file)

print("Saved:", train_file, "and", test_file)

from torch.utils.data import Dataset

class QuotesDataset(Dataset):
    def __init__(self, file_path, tokenizer, block_size=64):
        with open(file_path, "r", encoding="utf-8") as f:
            text = f.read()

        token_ids = tokenizer.encode(text)

        self.examples = []
        for i in range(0, len(token_ids) - block_size + 1, block_size):
            chunk = token_ids[i : i + block_size]
            self.examples.append(chunk)

    def __len__(self):
        return len(self.examples)

    def __getitem__(self, idx):
        return torch.tensor(self.examples[idx], dtype=torch.long)


train_dataset = QuotesDataset(train_file, tokenizer, block_size=64)
test_dataset = QuotesDataset(test_file, tokenizer, block_size=64)

print("Train examples:", len(train_dataset))
print("Test examples:", len(test_dataset))

from transformers import DataCollatorForLanguageModeling, TrainingArguments, Trainer

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False   # mlm=False because GPT-2 predicts the next word, not a masked word
)

training_args = TrainingArguments(
    output_dir="gpt2-quotes",
    num_train_epochs=3,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    eval_strategy="epoch",     # evaluate on test set after every epoch
    save_steps=500,
    logging_steps=20,
    learning_rate=5e-5,
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
)

trainer.train()

save_path = "gpt2-quotes-final"
model.save_pretrained(save_path)
tokenizer.save_pretrained(save_path)
print("Model saved at:", save_path)

def generate_quote(prompt, max_length=40):
    input_ids = tokenizer.encode(prompt, return_tensors="pt").to(device)
    output = model.generate(
        input_ids,
        max_length=max_length,
        do_sample=True,
        top_p=0.9,
        top_k=50,
        temperature=0.8,
        no_repeat_ngram_size=2,
        pad_token_id=tokenizer.eos_token_id
    )
    return tokenizer.decode(output[0], skip_special_tokens=True)


prompts = ["Once upon a time", "Love is", "The secret to happiness is", "Life is"]

for p in prompts:
    print("Prompt:", p)
    print("Generated:", generate_quote(p))
    print("-" * 80)

prompt = "Once upon a time"
input_ids = tokenizer.encode(prompt, return_tensors="pt").to(device)

print("Greedy search:")
out = model.generate(input_ids, max_length=40, pad_token_id=tokenizer.eos_token_id)
print(tokenizer.decode(out[0], skip_special_tokens=True))
print()

print("Beam search:")
out = model.generate(input_ids, max_length=40, num_beams=5, no_repeat_ngram_size=2,
                      early_stopping=True, pad_token_id=tokenizer.eos_token_id)
print(tokenizer.decode(out[0], skip_special_tokens=True))
print()

print("Top-k sampling:")
out = model.generate(input_ids, max_length=40, do_sample=True, top_k=50,
                      pad_token_id=tokenizer.eos_token_id)
print(tokenizer.decode(out[0], skip_special_tokens=True))
print()

print("Top-p sampling:")
out = model.generate(input_ids, max_length=40, do_sample=True, top_p=0.9, top_k=0,
                      pad_token_id=tokenizer.eos_token_id)
print(tokenizer.decode(out[0], skip_special_tokens=True))

import math

eval_results = trainer.evaluate()
eval_loss = eval_results["eval_loss"]
perplexity = math.exp(eval_loss)

print("Eval loss:", eval_loss)
print("Perplexity:", perplexity)